# This is a basic file to enable use of binder with the Jupyter notebooks
# embedded in examples/external/notebooks

name: notebooks

# Load dependencies - add modules here if you need them
dependencies:
  - python
# Maths related
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
# Molecular modelling
  - ase
  - wulffpack
  - asap3
  - catlearn
# Necessary for online atom viewing
  - nglview
  - ipywidgets